language: python
python:
  - 3.7

install:
  - pip install -q pipenv codecov
  - pipenv sync --dev

script:
  - flake8
  - pytest libpythonpro_github --cov=libpythonpro_github

after_success:
  - codecov